require 'git'
require 'thor'
require 'yaml'
require 'singleton'

require 'badger/version'
require 'badger/config'
require 'badger/badger'
require 'badger/service'
require 'badger/license'
require 'badger/rubygem'
require 'badger/helpers'
require 'badger/badge'
require 'badger/bonus'
